name: Pull and Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull changes
        run: git pull

      - name: Make changes
        run: echo "New change" >> file.txt

      - name: Commit changes
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
          git commit -am "Add new change"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
